/** Generated by ../index.ts: a loader for every skin's built entry, keyed by the skin's directory name. */
declare module 'virtual:fit-check/skins' {
  export const html: Record<string, () => Promise<unknown>>;
  export const react: Record<string, () => Promise<unknown>>;
}
